spring.application.name=DATN

spring.datasource.url=jdbc:sqlserver://127.0.0.1:1433;databaseName=PolyShoesDB;encrypt=false;trustServerCertificate=true;sendStringParametersAsUnicode=true
spring.datasource.username=sa
spring.datasource.password=Lehuynhduc29@
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=true

app.jwt.secret=TGIqllBw2vKZsRHOmSm0a39M4Y7a0kipFX/aZASwkh4=
app.jwt.expiration-ms=900000
app.auth.session-inactivity-ms=1800000

spring.jackson.deserialization.accept-float-as-int=false

spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
spring.jackson.time-zone=Asia/Ho_Chi_Minh

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=lehuynhduc150303@gmail.com
spring.mail.password=igderjdcqbubyead
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000
